### ISSUE TITLE
unlink extract_dir in import utility

### ISSUE THREAD

**Issue by ggieling** [giterlizzi/dokuwiki-plugin-advanced#10]
Giuseppe,
Php reports an error after importing a namespace of files using the import utility as provided in the advanced utility.

Line 146 of /lib/plugins/advanced/admin/import.php reads 'unlink($extract_dir);'
The unlink (https://secure.php.net/manual/en/function.unlink.php) command in php is used to delete a file, but $extract_dir is a directory.
I think you intended to use rmdir() here.

I checked the /data/tmp directory and it indeed stil contains the directory with all the imported files.
I assume I can safely delete these tmp directories.

**Comment by giterlizzi** [comment]
Hi, thanks for reporting this issue. I have pushed a fix to this issue.

You can update the pligin?

Thanks.

At your disposal,
Joseph

**Comment by ggieling** [comment]
I will try later this week,
I'm not at home before thursday evening.

Gerben Gieling
IP Specialist

Synthon BV
Microweg 22 | P.O. Box 7071 | 6503 GN  Nijmegen | The Netherlands
T: +31(0)24 37 27 700 | F: +31(0)24 37 27 705 | www.synthon.com<http://www.synthon.com>

**Comment by ggieling** [comment]
Giuseppe,

I found some time to test tonight.
The new version produces a different error. The rmdir() function  can
only work on an empty directory.  Unfortunately there is no flag to
delete a directory recursively.

The php manualpage includes some example code blocks to recursively
delete an entire tree.  I think the code of <https://php.net/manual/en
/function.rmdir.php#110489> is quite elegant.


Gerben

On Mon, 2018-02-26 at 06:48 -0800, Giuseppe Di Terlizzi wrote:
> Hi, thanks for reporting this issue. I have pushed a fix to this
> issue.
>
> You can update the pligin?
>
> Thanks.
>
> At your disposal,
> Joseph
>
>

________________________________

This e-mail message and its attachments are subject to the disclaimer published at the following website of Synthon: http://www.synthon.com/information/disclaimer-e-mail-messages

**Comment by giterlizzi** [comment]
Hi,
thanks for your solution!
I have found a DokuWiki function can recursively delete all files and subdirectory.

Joseph
