### ISSUE TITLE
Almost empty page

### ISSUE THREAD

**Issue by martk70** [giterlizzi/dokuwiki-plugin-advanced#2]
Interested in this plugin, however I only see the header and a promising but non responding index.

![2016 04 06_141553](https://cloud.githubusercontent.com/assets/13997873/14316208/14a65780-fc02-11e5-99ee-9ad744ec85f7.jpg)

**Comment by giterlizzi** [comment]
Hi! Thanks for using my plugin. This is similar issue (for SQLite Plugin) fixed in "develop" branch of Bootstrap3 template (https://github.com/LotarProject/dokuwiki-template-bootstrap3/commit/3d95a6ffa6a14a54fa91e12f98d9826d444662d7).

**Comment by mukrop** [comment]
Hi, running Dokuwiki 2017-02-19b "Frusterick Manners" and up-to-date Advanced config plugin (2016-10-24), I'm having the issue described here. Any idea what may be causing it?

**Comment by nurzu** [comment]
I'm facing the same issue. 

**Versions**
[Bootstrap3 Template] v2018-02-16 (up-to-date 2018-03-31)
[DokuWiki] Release 2017-02-19e “Frusterick Manners”
[Plugins] Advanced Plugin (up-to-date 2018-03-31)
[Plugins] Icons (up-to-date 2018-03-31)
[Plugins] Bootswrapper (up-to-date 2018-03-31)
[Browser] All modern browsers
