### ISSUE TITLE
Error writing style files

### ISSUE THREAD

**Issue by GJRobert** [giterlizzi/dokuwiki-plugin-advanced#5]
Ciao Giuseppe~

I've got an error editing style sheets, e.g. when I want to save the "screen" stylesheet, messages like:

> Creating directory / failed
> Writing / failed
> Unable to save file!

are returned.

For reference, I also attach the screen I'm seeing when editing styles. ![dokuwiki-advanced-style-error](https://cloud.githubusercontent.com/assets/655584/16288045/8a1ee3ec-391a-11e6-95d8-be846f34ebda.png) Notice the "/" path on the bottom-right corner, as circled in green.

**Comment by giterlizzi** [comment]
Hi! Thanks for reporting this issue.

Can you paste the full url of this page ?

Joseph

**Comment by GJRobert** [comment]
Ciao,

The URL should be sth like http://ciangbrides.myds.me/dokuwiki/start?do=admin&page=advanced&type=userstyle&file=screen&sectok=0882a7868101d5047d4c04332d5bd3c8

**But there is a good news**: after upgrading to 2015 Detritus (I just did that, because my DokuWiki install was 2014), the plugin can now grab my "/volume1/web/dokuwiki/conf/userstyle.css" and other CSS files, not just the wrong path "/", and my editions are successful now.

So I guess this bug can be closed now. Thanks for your kindness!

**Comment by giterlizzi** [comment]
Thanks for your feedback ;)
