### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in ../lib/plugins/advanced/admin/config.php on line 410

### ISSUE THREAD

**Issue by glaukos78** [giterlizzi/dokuwiki-plugin-advanced#7]
I have this warning on the head page Advanced configuration.
 
Warning: Invalid argument supplied for foreach() in ../lib/plugins/advanced/admin/config.php on line 410

Please for your advice

**Comment by giterlizzi** [comment]
Hi @glaukos78,
this warning is displayed on every page / section of Advanced plugin ?

Best regards,
Joseph

**Comment by glaukos78** [comment]
Good evening,

Appeared only section Advanced plugin

Thanks

**Comment by ssahara** [comment]
The PHP warning `Invalid argument supplied for foreach() in config.php on line 410` caused when  `$toc_plugins` is not defined if *explain* plugin is not installed.

I suggest to initialize $toc_plugins at just prior foreach loop on line 375.
```
    $toc_plugins = array(); // initialize toc items of plugins
    foreach ($plugin_list as $plugin) {

      switch ($plugin) {
        case 'explain':
          $toc_plugins['explain.conf'] = 'Explain';
          break;
      }

    }
```

**Comment by giterlizzi** [comment]
Thanks! :+1:
